import type { Movie, Sighting } from "./whererat";

/**
 * In-repo catalog starter rows (real IMDb `tt` IDs) for local dev, demos, and screenshots.
 * Re-exported via `movies` / `sightings` in `whererat.ts` and written to `db/seed.json`
 * by `npm run seed:postgres:export`. Posters are placeholders until you resync from OMDb.
 */
export const catalogSeedMovies: Movie[] = [
  {
    id: "movie-tt0382932",
    slug: "ratatouille",
    title: "Ratatouille",
    releaseYear: 2007,
    runtimeMinutes: 111,
    genres: ["Animation", "Adventure", "Comedy", "Family"],
    posterTone: "bg-orange-900",
    posterUrl:
      "https://placehold.co/600x900/ea580c/fef3c7/png?text=Ratatouille+%282007%29",
    backdropUrl:
      "https://placehold.co/1200x600/7c2d12/fef3c7/png?text=Ratatouille",
    posterAlt: "Ratatouille (2007) placeholder poster",
    externalIds: { imdb: "tt0382932", tmdb: "1918" },
    summary:
      "A rat who can cook forms an unlikely partnership with a clumsy kitchen helper at a famous Paris restaurant.",
    metadata: {
      tagline: "He's dying to become a chef.",
      rating: "G",
      director: "Brad Bird, Jan Pinkava",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
      ratFacts: [
        "Pixar’s lead animators studied live rats to nail Remy’s gait and whisker acting.",
      ],
    },
  },
  {
    id: "movie-tt0093779",
    slug: "the-princess-bride",
    title: "The Princess Bride",
    releaseYear: 1987,
    runtimeMinutes: 98,
    genres: ["Adventure", "Comedy", "Family", "Fantasy"],
    posterTone: "bg-rose-950",
    posterUrl:
      "https://placehold.co/600x900/be123c/fef3c7/png?text=The+Princess+Bride",
    backdropUrl:
      "https://placehold.co/1200x600/451a03/fef3c7/png?text=Fire+Swamp",
    posterAlt: "The Princess Bride (1987) placeholder poster",
    externalIds: { imdb: "tt0093779", tmdb: "2493" },
    summary:
      "A farmhand turned pirate pursues his true love alongside a giant, a swordsman, and a vengeful Spaniard.",
    metadata: {
      tagline: "The story of a man and his will to survive.",
      rating: "PG",
      director: "Rob Reiner",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0097576",
    slug: "indiana-jones-and-the-last-crusade",
    title: "Indiana Jones and the Last Crusade",
    releaseYear: 1989,
    runtimeMinutes: 127,
    genres: ["Action", "Adventure"],
    posterTone: "bg-stone-600",
    posterUrl:
      "https://placehold.co/600x900/44403c/fef3c7/png?text=Last+Crusade",
    backdropUrl:
      "https://placehold.co/1200x600/292524/fef3c7/png?text=Indiana+Jones",
    posterAlt: "Indiana Jones and the Last Crusade (1989) placeholder poster",
    externalIds: { imdb: "tt0097576", tmdb: "89" },
    summary:
      "Indiana Jones and his father chase Nazi agents to recover the Holy Grail before it falls into the wrong hands.",
    metadata: {
      tagline: "Have the adventure of your life keeping up with the Joneses.",
      rating: "PG-13",
      director: "Steven Spielberg",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0407887",
    slug: "the-departed",
    title: "The Departed",
    releaseYear: 2006,
    runtimeMinutes: 151,
    genres: ["Crime", "Drama", "Thriller"],
    posterTone: "bg-red-900",
    posterUrl:
      "https://placehold.co/600x900/450a0a/fef3c7/png?text=The+Departed",
    backdropUrl:
      "https://placehold.co/1200x600/1c1917/fef3c7/png?text=Boston",
    posterAlt: "The Departed (2006) placeholder poster",
    externalIds: { imdb: "tt0407887", tmdb: "1422" },
    summary:
      "An undercover cop and a mole in the police infiltrate an Irish gang in Boston.",
    metadata: {
      tagline: "Lies. Betrayal. Sacrifice. How far will you take it?",
      rating: "R",
      director: "Martin Scorsese",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0318916",
    slug: "willard",
    title: "Willard",
    releaseYear: 2003,
    runtimeMinutes: 100,
    genres: ["Drama", "Horror"],
    posterTone: "bg-neutral-800",
    posterUrl: "https://placehold.co/600x900/171717/fef3c7/png?text=Willard",
    backdropUrl:
      "https://placehold.co/1200x600/0a0a0a/fef3c7/png?text=Rats",
    posterAlt: "Willard (2003) placeholder poster",
    externalIds: { imdb: "tt0318916", tmdb: "10875" },
    summary:
      "A lonely man trains an army of rats to exact revenge on his cruel boss—and things spiral out of control.",
    metadata: {
      tagline: "Where your problems disappear.",
      rating: "PG-13",
      director: "Glen Morgan",
      originalLanguage: "English",
      productionCountries: ["United States", "Canada"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0084649",
    slug: "the-secret-of-nimh",
    title: "The Secret of NIMH",
    releaseYear: 1982,
    runtimeMinutes: 82,
    genres: ["Animation", "Adventure", "Drama"],
    posterTone: "bg-slate-800",
    posterUrl:
      "https://placehold.co/600x900/5b21b6/fef3c7/png?text=NIMH",
    backdropUrl:
      "https://placehold.co/1200x600/1e1b4b/fef3c7/png?text=NIMH",
    posterAlt: "The Secret of NIMH (1982) placeholder poster",
    externalIds: { imdb: "tt0084649", tmdb: "11774" },
    summary:
      "A field mouse must save her sick son with help from a society of genetically enhanced rats.",
    metadata: {
      tagline: "Right before your eyes and beyond your wildest dreams.",
      rating: "G",
      director: "Don Bluth",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0424095",
    slug: "flushed-away",
    title: "Flushed Away",
    releaseYear: 2006,
    runtimeMinutes: 85,
    genres: ["Animation", "Action", "Adventure", "Comedy"],
    posterTone: "bg-slate-900",
    posterUrl:
      "https://placehold.co/600x900/1e293b/fef3c7/png?text=Flushed+Away",
    backdropUrl:
      "https://placehold.co/1200x600/0f172a/fef3c7/png?text=Sewer+Rats",
    posterAlt: "Flushed Away (2006) placeholder poster",
    externalIds: { imdb: "tt0424095", tmdb: "11765" },
    summary:
      "A pampered pet rat is flushed into the London sewers and teams up with scavenger rats to face a toad kingpin.",
    metadata: {
      tagline: "Someone's going to pay...",
      rating: "PG",
      director: "Sam Fell, David Bowers",
      originalLanguage: "English",
      productionCountries: ["United States", "United Kingdom"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0090633",
    slug: "an-american-tail",
    title: "An American Tail",
    releaseYear: 1986,
    runtimeMinutes: 80,
    genres: ["Animation", "Adventure", "Comedy", "Drama"],
    posterTone: "bg-amber-950",
    posterUrl:
      "https://placehold.co/600x900/78350f/fef3c7/png?text=Fievel",
    backdropUrl:
      "https://placehold.co/1200x600/451a03/fef3c7/png?text=America",
    posterAlt: "An American Tail (1986) placeholder poster",
    externalIds: { imdb: "tt0090633", tmdb: "11003" },
    summary:
      "A young mouse emigrates from Russia to New York and searches for his family with help from other downtrodden rodents.",
    metadata: {
      tagline: "Meet Fievel. In his search to find his family, he discovered America.",
      rating: "G",
      director: "Don Bluth",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0091149",
    slug: "the-great-mouse-detective",
    title: "The Great Mouse Detective",
    releaseYear: 1986,
    runtimeMinutes: 74,
    genres: ["Animation", "Adventure", "Family"],
    posterTone: "bg-stone-800",
    posterUrl:
      "https://placehold.co/600x900/292524/fef3c7/png?text=Basil",
    backdropUrl:
      "https://placehold.co/1200x600/1c1917/fef3c7/png?text=London",
    posterAlt: "The Great Mouse Detective (1986) placeholder poster",
    externalIds: { imdb: "tt0091149", tmdb: "10534" },
    summary:
      "Mouse sleuth Basil of Baker Street hunts a peg-legged bat and a ratty crime boss under the streets of Victorian London.",
    metadata: {
      tagline: "The world's greatest mouse detective!",
      rating: "G",
      director: "John Musker, Ron Clements, Dave Michener, Burny Mattinson",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0119715",
    slug: "mousehunt",
    title: "Mousehunt",
    releaseYear: 1997,
    runtimeMinutes: 99,
    genres: ["Comedy", "Family"],
    posterTone: "bg-stone-600",
    posterUrl:
      "https://placehold.co/600x900/78716c/fef3c7/png?text=Mousehunt",
    backdropUrl:
      "https://placehold.co/1200x600/44403c/fef3c7/png?text=Mansion",
    posterAlt: "Mousehunt (1997) placeholder poster",
    externalIds: { imdb: "tt0119715", tmdb: "10510" },
    summary:
      "Two luckless brothers inherit a decrepit mansion and wage an escalating war with a single crafty mouse.",
    metadata: {
      tagline: "Who's hunting who?",
      rating: "PG",
      director: "Gore Verbinski",
      originalLanguage: "English",
      productionCountries: ["United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
  {
    id: "movie-tt0120595",
    slug: "stuart-little",
    title: "Stuart Little",
    releaseYear: 1999,
    runtimeMinutes: 84,
    genres: ["Adventure", "Comedy", "Family", "Fantasy"],
    posterTone: "bg-slate-800",
    posterUrl:
      "https://placehold.co/600x900/292524/fef3c7/png?text=Stuart+Little",
    backdropUrl:
      "https://placehold.co/1200x600/1e293b/fef3c7/png?text=NYC",
    posterAlt: "Stuart Little (1999) placeholder poster",
    externalIds: { imdb: "tt0120595", tmdb: "10068" },
    summary:
      "The Little family adopts a modestly sophisticated mouse—but their wary cat refuses to coexist peacefully.",
    metadata: {
      tagline: "The Little family just got bigger.",
      rating: "PG",
      director: "Rob Minkoff",
      originalLanguage: "English",
      productionCountries: ["Germany", "United States"],
      metadataProvider: "IMDb seed",
      lastSyncedAt: "2026-05-08",
    },
  },
];

export const catalogSeedSightings: Sighting[] = [
  // Ratatouille
  {
    id: "sighting-tt0382932-remy-intro",
    movieId: "movie-tt0382932",
    timestamp: "4%",
    title: "Remy surfaces in Gusteau’s skylight fantasy",
    description:
      "Remy scouts the rooftop and Paris skyline—our first prolonged look at the hero rat before kitchen chaos kicks in.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed", "screening-note"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0382932-rat-swarm-exit",
    movieId: "movie-tt0382932",
    timestamp: "11%",
    title: "Whole clan bolts from the shotgun cottage",
    description:
      "The colony scatters Remy-forward through planks and netting—crowd choreography that reads as a swarm early on.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 12,
  },
  {
    id: "sighting-tt0382932-finale-tasting",
    movieId: "movie-tt0382932",
    timestamp: "94%",
    title: "Rémy team serves the unknowing critic",
    description:
      "The rat-guided service peaks as ratatouille is plated; Remy directs from concealment—a finale beat built around rodents in the workflow.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: true,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 2,
    curatorNote: "Spoiler-flagged ending kitchen beat.",
  },
  // Princess Bride — ROUS
  {
    id: "sighting-tt0093779-fire-swamp-rous",
    movieId: "movie-tt0093779",
    timestamp: "48%",
    title: "Rodents Of Unusual Size in the Fire Swamp",
    description:
      "Wesley tussles with a ROUS in the mud pits—explicit rat-adjacent creature design called out by name on screen.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed", "quoted-dialogue"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0093779-more-rusi",
    movieId: "movie-tt0093779",
    timestamp: "50%",
    title: "Follow-up scramble in thickets",
    description:
      "Buttercup and Wesley are still dealing with swamp predators right after the first ROUS—brief additional creature beats.",
    prominence: "blink-and-miss",
    sceneType: "live-action",
    spoiler: false,
    confidence: "likely",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 2,
  },
  {
    id: "sighting-tt0093779-rus-namedrop",
    movieId: "movie-tt0093779",
    timestamp: "44%",
    title: "\"Rodents Of Unusual Size? I don't think they exist.\"",
    description:
      "Dialog setup immediately before Fire Swamp action—bookmark moment for rewatches.",
    prominence: "background",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    curatorNote: "No rats on-screen yet—dialog-only beat leading into ROUS scenes.",
  },
  // Indiana Jones Last Crusade
  {
    id: "sighting-tt0097576-catacombs-flood",
    movieId: "movie-tt0097576",
    timestamp: "38%",
    title: "Flooded crypt rat surge",
    description:
      "Indy and Elsa hurry through Byzantine tunnels while countless rats skim the oily water—it’s swarm-level coverage.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 30,
  },
  {
    id: "sighting-tt0097576-vertical-climb",
    movieId: "movie-tt0097576",
    timestamp: "40%",
    title: "Rats pour past the grate climb",
    description:
      "The heroes ascend a shaft as rats tumble around them mid-escape—the beat continues the catacombs choreography.",
    prominence: "background",
    sceneType: "live-action",
    spoiler: false,
    confidence: "likely",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 20,
  },
  {
    id: "sighting-tt0097576-henry-snark",
    movieId: "movie-tt0097576",
    timestamp: "36%",
    title: "Henry fumes about rodents before the scramble",
    description:
      "Prefatory hallway banter tees up rats as an environmental hazard—not on-screen rats yet.",
    prominence: "background",
    sceneType: "live-action",
    spoiler: false,
    confidence: "needs-source",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
  },
  // The Departed
  {
    id: "sighting-tt0407887-finale-balcony",
    movieId: "movie-tt0407887",
    timestamp: "99%",
    title: "Final balcony rat symbolism",
    description:
      "Scorsese famously holds on a rodent crossing sunlight after the climax—explicit rat punctuation shot.",
    prominence: "scene-stealer",
    sceneType: "symbolic",
    spoiler: true,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0407887-micro-rat-snippet",
    movieId: "movie-tt0407887",
    timestamp: "18%",
    title: "Alley grime beat (blink-and-miss)",
    description:
      "Urban texture shots occasionally catch vermin ambience while Boston surveillance threads move—thin but catalogued for rewind hunters.",
    prominence: "blink-and-miss",
    sceneType: "live-action",
    spoiler: false,
    confidence: "needs-source",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog (needs rewatch confirmation)",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0407887-wiretap-montage",
    movieId: "movie-tt0407887",
    timestamp: "52%",
    title: "Warehouse rat during tech sweep",
    description:
      "Crew anecdotes flag a fleeting rat silhouette during cramped stakeout setups—moderators can downgrade if rewatches disagree.",
    prominence: "blink-and-miss",
    sceneType: "live-action",
    spoiler: false,
    confidence: "likely",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["community-citation"],
    approximateRatCount: 1,
  },
  // Willard (2003)
  {
    id: "sighting-tt0318916-office-invasion",
    movieId: "movie-tt0318916",
    timestamp: "33%",
    title: "Rat army storms the bullpen",
    description:
      "Willard unleashes coordinated swarms indoors—crowd CGI + animatronics with dozens of villains on desktops.",
    prominence: "scene-stealer",
    sceneType: "swarm",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 40,
  },
  {
    id: "sighting-tt0318916-ben-buddy",
    movieId: "movie-tt0318916",
    timestamp: "8%",
    title: "Ben earns the spotlight",
    description:
      "Willard nurses the white rat’s bond—solo close-ups used for marketing beats and meme stills alike.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0318916-basement",
    movieId: "movie-tt0318916",
    timestamp: "20%",
    title: "Colony rehearsals below the stairs",
    description:
      "Basement cages overflow as Willard inventories growing numbers—a mid-film escalation before office chaos.",
    prominence: "background",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 15,
  },
  // Secret of NIMH
  {
    id: "sighting-tt0084649-moving-the-brick",
    movieId: "movie-tt0084649",
    timestamp: "15%",
    title: "Council of uplifted rats",
    description:
      "Nicodemus faction debates moving the Fitzgibbon homestead—crowded rat parliament blocking shots.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 18,
  },
  {
    id: "sighting-tt0084649-dragon-threat",
    movieId: "movie-tt0084649",
    timestamp: "28%",
    title: "Dragon the cat hunts Mrs. Brisby",
    description:
      "Domestic showdown where rodent heroine navigates predator territory—stress scene with repeated rat silhouettes.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0084649-machinery-finale",
    movieId: "movie-tt0084649",
    timestamp: "86%",
    title: "Pulleys, chains, rats everywhere",
    description:
      "Finale hoist sequence strings dozens of cooperating rats hauling concrete—crowd choreography capstone.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 35,
  },
  // Flushed Away
  {
    id: "sighting-tt0424095-sewer-clan",
    movieId: "movie-tt0424095",
    timestamp: "12%",
    title: "Jammy Dodgers in the borough",
    description:
      "Scavenger sewer rats bustle through their tube-and-tinsel city—establishing rodents as the backbone of the underworld.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 25,
  },
  {
    id: "sighting-tt0424095-speedboat-chase",
    movieId: "movie-tt0424095",
    timestamp: "55%",
    title: "Soap-dish boat siege",
    description:
      "Rodent sailors race sluice currents with dozens aboard makeshift decking—crowd shots full of scrambling rats.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 18,
  },
  {
    id: "sighting-tt0424095-toad-hideout",
    movieId: "movie-tt0424095",
    timestamp: "70%",
    title: "Throngs under the amphibian tyrant",
    description:
      "The toad’s court keeps rat gangs in frame as muscle during the climax—heavy rodent choreography in the showdown.",
    prominence: "background",
    sceneType: "animated",
    spoiler: false,
    confidence: "likely",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 12,
  },
  // An American Tail — Warren T is a rat posing as a mouse
  {
    id: "sighting-tt0090633-warren-t-intro",
    movieId: "movie-tt0090633",
    timestamp: "22%",
    title: "Warren T. Rat’s alley scheme",
    description:
      "The con-artist antagonist—a rat disguised among mice—sets up alley swindles; extended close-ups confirm species.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0090633-mouse-market",
    movieId: "movie-tt0090633",
    timestamp: "30%",
    title: "Crowded immigrant rodents",
    description:
      "Mice pack tenements and docks; swarms lend rat-adjacent coverage even when hero mice dominate the frame.",
    prominence: "background",
    sceneType: "animated",
    spoiler: false,
    confidence: "likely",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 35,
  },
  {
    id: "sighting-tt0090633-sewer-tunnel",
    movieId: "movie-tt0090633",
    timestamp: "45%",
    title: "Storm-drain scramble",
    description:
      "Fievel threads storm pipes where mixed rodent casts push through waterlogged tunnels—crowd silhouettes abound.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 8,
  },
  // The Great Mouse Detective — Professor Ratigan
  {
    id: "sighting-tt0091149-ratigan-intro",
    movieId: "movie-tt0091149",
    timestamp: "18%",
    title: "Professor Ratigan takes center stage",
    description:
      "The Napoleon of crime is an anthropomorphic rat—large-scale villain beats keep him on-camera throughout.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0091149-bar-song",
    movieId: "movie-tt0091149",
    timestamp: "32%",
    title: "Ratigan’s musical riot",
    description:
      "Thug rodents back Ratigan during the villain song—chorus choreography packed with hench-rats.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 16,
  },
  {
    id: "sighting-tt0091149-clocktower-finale",
    movieId: "movie-tt0091149",
    timestamp: "88%",
    title: "Clock-tower showdown crowd",
    description:
      "Basil battles Ratigan atop Big Ben with rat gangs swarming gears—crowd peril capstone.",
    prominence: "scene-stealer",
    sceneType: "animated",
    spoiler: true,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 12,
    curatorNote: "Spoiler: climax atop the clock tower.",
  },
  // Mousehunt
  {
    id: "sighting-tt0119715-string-cheese-trap",
    movieId: "movie-tt0119715",
    timestamp: "15%",
    title: "Industrial mouse trap escalation",
    description:
      "The sole mouse dominates slapstick—but every contraption gag keeps the rodent in hero close-up.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0119715-chase-mansion",
    movieId: "movie-tt0119715",
    timestamp: "40%",
    title: "Mansion chase choreography",
    description:
      "Brothers Vs. mouse through parquet and pipes—animal performer shots are unmistakable rewinds.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0119715-table-finale",
    movieId: "movie-tt0119715",
    timestamp: "92%",
    title: "Formal dinner chaos",
    description:
      "The mouse hijacks centerpiece service—table-wide gag coverage with tactile rodent antics.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  // Stuart Little
  {
    id: "sighting-tt0120595-family-photo",
    movieId: "movie-tt0120595",
    timestamp: "10%",
    title: "Tiny brother joins the portrait",
    description:
      "Stuart settles into the Manhattan brownstone—the mouse protagonist is framed like a sibling in montage beats.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0120595-cat-confront",
    movieId: "movie-tt0120595",
    timestamp: "42%",
    title: "Snowbell stalks Stuart",
    description:
      "Housecat rivalries hinge on spotting the mouse indoors—stalking choreography through ductwork.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
  {
    id: "sighting-tt0120595-boat-race",
    movieId: "movie-tt0120595",
    timestamp: "75%",
    title: "Central Park model-boat derby",
    description:
      "Stuart crews a miniature schooner amid crowds—the set piece keeps puppet/CGI rodent foregrounded.",
    prominence: "scene-stealer",
    sceneType: "live-action",
    spoiler: false,
    confidence: "verified",
    verificationState: "verified",
    verifiedBy: "WhereRat seed catalog",
    sourceIds: ["imdb-seed"],
    approximateRatCount: 1,
  },
];
